import React from "react";
import type { Metadata } from "next";

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, Layout } from "antd";

import MainContent from "./MainContent/page";
import MainFooter from "./mainfooter/page";
import MainSider from "./mainsider/page";
import Mainbottombtn from "./mainbottombtn/page";


import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const colorPrimary = "#ac46ff";
const colorInfo = "#ac46ff";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider

            theme={{
              "token": {
                colorPrimary,
                colorInfo,
              }
            }}
          >
            <Layout hasSider>
              <MainSider />

              <Layout>

                <MainContent>
                  {children}
                </MainContent>
                <Mainbottombtn />

                <MainFooter />

              </Layout>
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
